(function(root){
 const m=n=>Math.round(Number(n||0)*100)/100,sum=(r,f)=>m(r.reduce((s,x)=>s+Math.round(f(x)*100),0)/100);
 function partner(rows,who,from='',to=''){const all=rows.filter(r=>r.partner===who).sort((a,b)=>a.date.localeCompare(b.date)||(a.sourceRow||0)-(b.sourceRow||0)),opening=sum(all.filter(r=>from&&r.date<from),r=>r.credit-r.debit);let balance=opening;const selected=all.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to)).map(r=>({...r,balance:balance=m(balance+r.credit-r.debit)}));return {opening,rows:selected,closing:balance,debit:sum(selected,r=>r.debit),credit:sum(selected,r=>r.credit)};}
 function shares(rows,year){return Array.from({length:12},(_,i)=>{const month=year+'-'+String(i+1).padStart(2,'0'),rs=rows.filter(r=>r.date?.startsWith(month));return {month,amount:sum(rs,r=>r.amount),amrShare:sum(rs,r=>r.amrShare),amrPaid:sum(rs,r=>r.amrPaid),amrBalance:sum(rs,r=>r.amrShare-r.amrPaid),lamiaaShare:sum(rs,r=>r.lamiaaShare),lamiaaPaid:sum(rs,r=>r.lamiaaPaid),lamiaaBalance:sum(rs,r=>r.lamiaaShare-r.lamiaaPaid)};});}
 function initialize(db){for(const k of ['projects','payments','expenses','charges','invoices','quotes','blocks','partnerLedger','expenseShares','importBatches'])db[k]??=[];return db;}
 function append(db,batch,records){initialize(db);if(db.importBatches.some(b=>b.fingerprint===batch.fingerprint))throw Error('هذا الملف مستورد بالفعل لهذا الحساب أو المشروع.');const keys=new Set([...db.payments,...db.expenses,...db.partnerLedger,...db.expenseShares].map(r=>r.importKey).filter(Boolean));for(const entry of records){if(keys.has(entry.importKey))throw Error('حركة مستوردة مكررة؛ أعد المعاينة.');keys.add(entry.importKey);const base={...entry,id:entry.id||crypto.randomUUID(),importBatch:batch.id};if(entry.kind==='partner')db.partnerLedger.push({...base,partner:batch.partner});else if(entry.kind==='shares'){const expenseId=crypto.randomUUID();db.expenses.push({...base,id:expenseId,project:'company-overhead',category:'Overhead',operatingCategory:'مصروفات تشغيل',party:'الشركة',reference:entry.reference||'IMPORT-'+expenseId});db.expenseShares.push({...base,expenseId});}else if(entry.kind==='receipt')db.payments.push({...base,direction:'in',method:entry.category||'تحويل نقدي',party:entry.party||batch.project?.client||'',project:batch.project.id,reference:entry.reference||'IMPORT-'+entry.id});else db.expenses.push({...base,project:batch.project.id,party:entry.party||'',category:entry.category||'Other direct costs',reference:entry.reference||'IMPORT-'+entry.id});}
 if(batch.project&&!db.projects.some(p=>p.id===batch.project.id))db.projects.push({...batch.project,source:batch.filename,accountingPending:true});else if(batch.project){const p=db.projects.find(p=>p.id===batch.project.id);p.source=p.source||batch.filename;p.accountingPending??=true;}
 db.importBatches.push({...batch,count:records.length,importedAt:new Date().toISOString()});return db;
 }
 const api={m,sum,partner,shares,initialize,append};root.TrustAccounting=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
