(async function(){
 const profile=await TrustAuth.ready;if(!profile)return;const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let clients=[],projects=[],t,issuing=false;
 const live=TrustAuth.enabled,status=$('#admin-status');
 function values(){return Object.fromEntries([...document.querySelectorAll('[data-template-field]')].map(i=>[i.dataset.templateField,i.value.trim()]));}
 function generate(){const v=values(),date=new Date($('#admin-date').value+'T12:00:00');v.contract_date=$('#admin-date').value;v.contract_day=Number.isNaN(date.valueOf())?'':new Intl.DateTimeFormat('ar-EG',{weekday:'long'}).format(date);$('#admin-body').value=t.body.replace(/\{\{(\w+)\}\}/g,(m,k)=>v[k]||m);$('#admin-reviewed').checked=false;preview();}
 function preview(){$('#admin-preview').innerHTML=$('#admin-body').value.split('\n').filter(Boolean).map(l=>'<p>'+esc(l)+'</p>').join('');}
 $('#admin-body').oninput=()=>{$('#admin-reviewed').checked=false;preview();};
 function field(key,value){const i=document.querySelector('[data-template-field="'+key+'"]');if(i)i.value=value||'';}
 function projectChanged(){const p=projects.find(p=>p.id===$('#admin-project').value);if(p)field('property_address',p.location);generate();}
 function clientChanged(){const c=clients.find(c=>c.id===$('#admin-client').value);if(!c)return;field('client_name',c.display_name);field('client_phone',c.phone);field('client_email',c.email);field('client_address',c.address);$('#admin-project').innerHTML=projects.filter(p=>p.client_id===c.id).map(p=>'<option value="'+esc(p.id)+'">'+esc(p.project_name)+'</option>').join('');projectChanged();}
 async function history(){if(!live)return;const {data,error}=await TrustAuth.client.from('client_contracts').select('*,client_contract_acceptances(*)').order('created_at',{ascending:false});if(error)throw error;$('#admin-contract-list').innerHTML=(data||[]).map(c=>'<article><details><summary>'+esc(c.client_name)+' · '+esc(c.version)+' · '+(c.client_contract_acceptances.length?'تم التوقيع':'بانتظار التوقيع')+'</summary><pre>'+esc(c.body)+'</pre>'+c.client_contract_acceptances.map(a=>'<p>الموقّع: '+esc(a.signer_name)+' · '+esc(a.signed_at)+' · مرجع: '+esc(a.id)+'</p>').join('')+'</details></article>').join('')||'<p>لم تصدر عقود بعد.</p>';}
 try{t=await fetch('contract-template.json').then(r=>r.json());$('#template-fields').innerHTML=t.fields.map(f=>'<label>'+esc(f.label)+'<input data-template-field="'+f.key+'" value="'+esc(f.default)+'" required></label>').join('');$('#admin-date').value=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 if(live){const results=await Promise.all([TrustAuth.client.from('clients').select('id,display_name,phone,email,address,auth_user_id'),TrustAuth.client.from('projects').select('id,client_id,project_name,location'),TrustAuth.client.from('contract_company_settings').select('fields').eq('id','main').maybeSingle()]);for(const r of results)if(r.error)throw r.error;clients=results[0].data.filter(c=>c.auth_user_id);projects=results[1].data;for(const f of t.fields.filter(f=>f.company)){if(results[2].data?.fields?.[f.key])field(f.key,results[2].data.fields[f.key]);}status.textContent='العقود تصدر للحسابات المرتبطة بالعملاء فقط. الأتعاب منفصلة عن قيمة المشروع الكلية.';}else{clients=[{id:'demo',display_name:'عميل تجريبي',phone:'01000000000',email:'client@example.test'}];projects=[{id:'demo',client_id:'demo',project_name:'مشروع تجريبي',location:'عنوان تجريبي'}];status.textContent='وضع مراجعة. لا يتم إصدار عقد فعلي أو حفظه.';}
 $('#admin-client').innerHTML=clients.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.display_name)+'</option>').join('');clientChanged();await history();
 }catch(e){console.error(e);status.textContent='تعذر تحميل بيانات التعاقد. تأكدي من تطبيق تحديث قاعدة البيانات رقم 004.';$('#issue-contract').disabled=true;}
 $('#admin-client').onchange=clientChanged;$('#admin-project').onchange=projectChanged;$('#generate-contract').onclick=generate;
 const saveCompany=document.createElement('button');saveCompany.type='button';saveCompany.className='contract-secondary';saveCompany.textContent='حفظ بيانات الشركة للعقود القادمة';$('#generate-contract').after(saveCompany);saveCompany.onclick=async()=>{if(!live){status.textContent='حفظ بيانات الشركة متاح عند الاتصال بقاعدة البيانات.';return;}const v=values(),fields=Object.fromEntries(t.fields.filter(f=>f.company).map(f=>[f.key,v[f.key]]));saveCompany.disabled=true;try{const {error}=await TrustAuth.client.from('contract_company_settings').upsert({id:'main',fields});if(error)throw error;status.textContent='تم حفظ بيانات الشركة، وستُملأ تلقائيًا في العقود القادمة.';}catch(e){console.error(e);status.textContent='تعذر حفظ بيانات الشركة. أعيدي المحاولة.';}finally{saveCompany.disabled=false;}};
 $('#contract-admin-form').onsubmit=async e=>{e.preventDefault();if(issuing)return;const body=$('#admin-body').value.trim();if(/\{\{|\.{3,}|…/.test(body)||body.length<500){status.textContent='استكملي جميع البيانات الناقصة في النص قبل إصدار العقد.';status.scrollIntoView();return;}if(!live){status.textContent='المعاينة جاهزة. الإصدار الفعلي متاح عند الاتصال بقاعدة البيانات.';return;}issuing=true;$('#issue-contract').disabled=true;try{const v=values(),p=projects.find(p=>p.id===$('#admin-project').value);const {error}=await TrustAuth.client.from('client_contracts').insert({client_id:$('#admin-client').value,version:$('#admin-version').value.trim(),title:t.title,body,future_forms:t.futureForms,client_name:v.client_name,details:{'العميل':v.client_name,'الشركة':v.company_name,'المشروع':p.project_name,'العقار':v.property_address,'الأتعاب':v.fee,'تاريخ العقد':$('#admin-date').value},created_by:profile.id});if(error)throw error;status.textContent='تم إصدار العقد. يلزم العميل توقيعه قبل دخول البوابة.';await history();$('#admin-reviewed').checked=false;}catch(e){console.error(e);status.textContent='تعذر إصدار العقد. تحققي من الاتصال وأعيدي المحاولة.';}finally{issuing=false;$('#issue-contract').disabled=false;}};
})();
