/* Local OpenXML reader. Macros, external links and formulas are never executed. */
(function(root){
 const norm=v=>String(v??'').replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/[\u064B-\u065F\u0640]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/\s+/g,' ').trim().toLowerCase();
 function number(v){if(v==null||String(v).trim()===''||/^[-—]$/.test(String(v).trim()))return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=norm(v).replace(/[٬,\s]/g,'').replace(/٫/g,'.').replace(/ج\.?م|جنيه|egp/gi,'');if(/^\(.*\)$/.test(s))s='-'+s.slice(1,-1);if(!/^-?\d+(\.\d+)?$/.test(s))return NaN;return Math.round(Number(s)*100)/100;}
 const months=['يناير','فبراير','مارس','ابريل','مايو','يونيو','يوليو','اغسطس','سبتمبر','اكتوبر','نوفمبر','ديسمبر'];
 const monthNames=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
 function iso(y,m,d){const x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d?x.toISOString().slice(0,10):'';}
 function date(v,year,date1904=false){if(typeof v==='number'){if(v<1||v>100000)return '';return new Date(Date.UTC(date1904?1904:1899,date1904?0:11,date1904?1:30)+Math.floor(v)*86400000).toISOString().slice(0,10);}const s=norm(v);let m;if((m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/)))return iso(+m[1],+m[2],+m[3]);if((m=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/)))return iso(+m[3],+m[2],+m[1]);if((m=s.match(/^(\d{1,2})[- /]([a-z]{3,9})(?:[- /](\d{2,4}))?$/))){const month=monthNames.indexOf(m[2].slice(0,3))+1;return month&&iso(m[3]?(m[3].length===2?2000+ +m[3]:+m[3]):+year,month,+m[1])||'';}for(let i=0;i<12;i++)if(s.includes(norm(months[i]))||s===String(i+1))return iso(+year,i+1,1);return '';}
 function xml(s){const d=new DOMParser().parseFromString(s,'application/xml');if(d.querySelector('parsererror'))throw Error('ملف Excel يحتوي XML غير صالح.');return d;}
 const nodes=(d,n)=>Array.from(d.getElementsByTagNameNS('*',n));
 const text=(d,n)=>nodes(d,n).map(x=>x.textContent).join('');
 const col=ref=>{let n=0;for(const c of ref.match(/^[A-Z]+/)?.[0]||'A')n=n*26+c.charCodeAt(0)-64;return n-1;};
 async function read(file){
  if(file.size>15*1024*1024)throw Error('الحد الأقصى للملف 15 ميجابايت.');if(!/\.xlsx$/i.test(file.name))throw Error('احفظ الملف بصيغة .xlsx ثم ارفعه.');
  const z=await JSZip.loadAsync(await file.arrayBuffer()),unzip=async(path,optional=false)=>{const e=z.file(path);if(!e){if(optional)return '';throw Error('ملف Excel غير مكتمل.');}const s=await e.async('string');if(s.length>12*1024*1024)throw Error('ورقة كبيرة جدًا. قسّم الملف إلى ملفات أصغر.');return s;};
  const w=xml(await unzip('xl/workbook.xml')),relations=xml(await unzip('xl/_rels/workbook.xml.rels')),shared=await unzip('xl/sharedStrings.xml',true),strings=shared?nodes(xml(shared),'si').map(si=>text(si,'t')):[],map=new Map(nodes(relations,'Relationship').filter(r=>r.getAttribute('TargetMode')!=='External').map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));
  const date1904=nodes(w,'workbookPr')[0]?.getAttribute('date1904')==='1';const sheets=[];let cells=0;
  for(const sh of nodes(w,'sheet')){const target=map.get(sh.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'));if(!target)continue;const path=target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'');if(path.includes('..'))throw Error('مسار ورقة غير صالح.');const d=xml(await unzip(path)),rows=[],missing=[];
   for(const r of nodes(d,'row')){const rowIndex=Number(r.getAttribute('r'))-1;if(rowIndex>20000)throw Error('الحد الأقصى 20 ألف صف لكل ورقة.');const row=[];for(const c of nodes(r,'c')){if(++cells>250000)throw Error('ملف كبير جدًا للاستيراد.');const ref=c.getAttribute('r'),i=col(ref);if(i>1000)throw Error('عدد الأعمدة كبير جدًا.');const type=c.getAttribute('t'),v=nodes(c,'v')[0]?.textContent;let value=type==='s'?strings[Number(v)]??'':type==='inlineStr'?text(c,'t'):type==='str'||type==='e'?v??'':v==null?'':Number(v);if(type==='e')value='#FORMULA_ERROR';if(nodes(c,'f').length&&!nodes(c,'v').length){value='#FORMULA_NO_CACHE';missing.push(ref);}row[i]=value;}rows[rowIndex]=row;}
   for(const merge of nodes(d,'mergeCell')){const [a,b]=merge.getAttribute('ref').split(':'),sr=+a.match(/\d+/)[0]-1,er=+b.match(/\d+/)[0]-1,sc=col(a),ec=col(b);if(sr>30||er>30)continue;for(let r=sr;r<=er;r++){rows[r]??=[];for(let c=sc;c<=ec;c++)rows[r][c]??=rows[sr]?.[sc];}}
   const top=rows.slice(0,10).flat().join(' '),y=top.match(/\b(20\d{2})\b/),meta={};for(let r=0;r<12;r++)for(let c=0;c<(rows[r]?.length||0);c++){const v=norm(rows[r][c]);for(const [label,key] of [['اسم المشروع','name'],['اسم العميل','client'],['رقم العقد','contractNumber'],['مهندس المشروع','engineer']])if(v===norm(label)){meta[key]=rows[r].slice(c+1).find(x=>x!==''&&x!=null&&norm(x)!==v)||'';}}
   sheets.push({name:sh.getAttribute('name'),rows,year:y?+y[1]:null,date1904,missing,meta});
  }
  return sheets;
 }
 function detect(sheet){for(let i=0;i<Math.min(40,sheet.rows.length);i++){const h=(sheet.rows[i]||[]).map(norm),has=s=>h.includes(norm(s));if(has('مدين')&&has('دائن'))return {type:'partner',header:i};if(h.filter(v=>v===norm('حصة المصروفات')).length>=2)return {type:'shares',header:i};if(has('البيان')&&(has('القيمة')||has('مستلم')||has('منصرف')))return {type:/مصروف/.test(sheet.name)?'expense':/تحصيل|مستلم|قبض/.test(sheet.name)?'receipt':'project',header:i};}return {type:'skip',header:-1};}
 function parse(sheet,options={}){
  const d=detect(sheet),type=options.type||d.type,header=options.header??d.header,year=options.year||sheet.year,rows=[];if(type==='skip')return rows;if(header<0)throw Error('حدد صف العناوين لهذه الورقة.');const h=sheet.rows[header].map(norm),above=sheet.rows[header-1]||[],cols={};const find=(names)=>h.findIndex(v=>names.some(n=>v===norm(n)));
  Object.assign(cols,{description:find(['البيان','بيان','الوصف']),date:find(['التاريخ','تاريخ']),amount:find(['القيمة','قيمة','المبلغ','مبلغ']),category:find(['البند','الفئة','التصنيف']),status:find(['الحالة','حالة البند']),notes:find(['ملاحظات','الملاحظات']),serial:find(['م','مسلسل','تسلسل']),debit:find(['مدين']),credit:find(['دائن']),balance:find(['رصيد','الرصيد']),received:find(['مستلم','تحصيلات']),expense:find(['منصرف','مصروفات']),reference:find(['المرجع','مرجع','رقم الفاتورة']),party:find(['المورد','المستفيد','اسم المورد','الطرف'])});
  if(type==='shares'){const shares=h.map((v,i)=>v===norm('حصة المصروفات')?i:-1).filter(i=>i>=0),paid=h.map((v,i)=>v===norm('المدفوع')?i:-1).filter(i=>i>=0),balances=h.map((v,i)=>v===norm('الرصيد')?i:-1).filter(i=>i>=0);for(const [partner,n] of [['amr',0],['lamiaa',1]]){let k=shares.findIndex(i=>norm(above[i]).includes(partner==='amr'?'عمرو':'لمي'));if(k<0)k=n;cols[partner+'Share']=shares[k];cols[partner+'Paid']=paid[k];cols[partner+'Balance']=balances[k];}}
  Object.assign(cols,options.columns||{});
  const cell=(row,key)=>cols[key]>=0?row[cols[key]]:'';
  if(cols.description<0)throw Error('عمود البيان غير موجود في '+sheet.name);
  for(let i=header+1;i<sheet.rows.length;i++){
   const r=sheet.rows[i];if(!r)continue;const desc=String(cell(r,'description')??'').trim(),n=norm(desc);if(!desc||/^(الاجمالي|اجمالي|المجموع|الفروقات|الفرق|اعتماد الادار|مدير المشروع|محاسب المشروع)/.test(n))continue;
   const item={id:crypto.randomUUID(),sheet:sheet.name,sourceRow:i+1,serial:String(cell(r,'serial')??''),description:desc,date:date(cell(r,'date'),year,sheet.date1904)||date(desc,year)||options.defaultDate||'',category:String(cell(r,'category')||''),status:String(cell(r,'status')||''),notes:String(cell(r,'notes')||''),reference:String(cell(r,'reference')||''),party:String(cell(r,'party')||''),issues:[],included:true};
   if(type==='partner'){item.kind='partner';item.debit=number(cell(r,'debit'))??0;item.credit=number(cell(r,'credit'))??0;item.sourceBalance=number(cell(r,'balance'));if(/افتتاح/.test(n)&&!item.debit&&!item.credit&&item.sourceBalance!=null){item.credit=Math.max(0,item.sourceBalance);item.debit=Math.max(0,-item.sourceBalance);item.opening=true;}if(!item.debit&&!item.credit&&item.sourceBalance==null)continue;if(!item.date&&/افتتاح/.test(n))item.date=iso(+year,1,1);item.amount=Math.max(item.debit,item.credit);}
   else if(type==='shares'){item.kind='shares';item.amount=number(cell(r,'amount'));for(const k of ['amrShare','amrPaid','lamiaaShare','lamiaaPaid'])item[k]=number(cell(r,k));if(item.amount==null&&item.amrShare==null&&item.lamiaaShare==null)continue;for(const partner of ['amr','lamiaa']){const expected=number(cell(r,partner+'Balance'));if(expected!=null&&Math.abs(expected-((item[partner+'Share']||0)-(item[partner+'Paid']||0)))>.011)item.issues.push('رصيد '+(partner==='amr'?'عمرو':'لمياء')+' غير مطابق للحصة ناقص المدفوع');}if(item.amount!=null&&item.amrShare!=null&&item.lamiaaShare!=null&&Math.abs(item.amrShare+item.lamiaaShare-item.amount)>.011)item.issues.push('مجموع الحصص لا يساوي المصروف');}
   else{item.kind=type==='project'?(number(cell(r,'received'))>0?'receipt':'expense'):type;item.amount=number(cell(r,item.kind==='receipt'&&cols.received>=0?'received':item.kind==='expense'&&cols.expense>=0?'expense':'amount'));if(item.amount==null)continue;if(type==='project'&&number(cell(r,'received'))>0&&number(cell(r,'expense'))>0)item.issues.push('الصف يحتوي مستلم ومنصرف؛ افصل الحركتين قبل الاستيراد');}
   if(!item.date)item.issues.push('تاريخ الحركة غير محدد');if(!Number.isFinite(item.amount)||item.amount<0)item.issues.push('القيمة غير صالحة');if(item.kind==='partner'&&(!Number.isFinite(item.debit)||!Number.isFinite(item.credit)||item.debit<0||item.credit<0))item.issues.push('راجع المدين والدائن');if(item.kind==='shares'&&['amrShare','amrPaid','lamiaaShare','lamiaaPaid'].some(k=>item[k]==null||!Number.isFinite(item[k])||item[k]<0))item.issues.push('استكمل حصص الشركاء والمدفوع (اكتب صفرًا عند عدم السداد)');if(r.some(c=>String(c).startsWith('#FORMULA')))item.issues.push('افتح الملف في Excel وأعد حساب الصيغ واحفظه');rows.push(item);
  }return rows;
 }
 const api={norm,number,date,read,detect,parse};root.TrustExcel=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
