/* Egyptian Arabic display layer. Stored values, option values and IDs stay unchanged. */
(function(){
const phrases={
 'Trust M | Financial module':'Trust M | حسابات المشاريع','Trust M | Owner Dashboard':'Trust M | لوحة المالك',
 'Sample financial workspace, separate from the owner dashboard’s sample portfolio. Records and invoice files stay on this browser and device; clearing browser data removes them. Nothing here is sent to clients automatically.':'دي نسخة تجريبية ببيانات منفصلة عن لوحة المالك. البيانات والفواتير محفوظة على المتصفح والجهاز ده بس، ومسح بيانات المتصفح بيمسحها. مفيش حاجة بتتبعت للعميل تلقائي.',
 'Records and invoice files stay on this browser and device; clearing browser data removes them.':'البيانات والفواتير محفوظة على الجهاز ده بس، ومسح بيانات المتصفح بيمسحها.',
 'Sample portfolio':'بيانات تجريبية','Sample data':'بيانات تجريبية','SAMPLE DATA':'بيانات تجريبية','DEMO RECORDS':'بيانات تجريبية','BROWSER DEMO':'نسخة تجريبية على المتصفح','Working demo':'نسخة تجريبية','Review mode':'وضع المراجعة','Stored in this browser only':'محفوظ على المتصفح ده بس','Browser-local records':'محفوظ على المتصفح ده بس','Demo records':'بيانات تجريبية','No automatic tax calculation':'الضرايب مش بتتحسب تلقائي',
 'Financial module':'حسابات المشاريع','FINANCIAL MODULE':'حسابات المشاريع','FINANCIAL MANAGEMENT':'إدارة الحسابات','Project finances.':'حسابات المشاريع','Financial sections':'أقسام الحسابات','Return to owner dashboard':'ارجع للوحة المالك','Owner dashboard':'لوحة المالك','Trust M owner dashboard':'لوحة مالك Trust M','Opening financial workspace…':'بنفتح حسابات المشاريع…',
 'Financial sheet':'كشف الحساب','Project overview':'ملخص المشاريع','Quotation blocks':'بنود المقايسات الجاهزة','Client statements':'كشوف حساب العملاء','Expenses & charges':'المصروفات وحساب العميل','Profit & loss':'الأرباح والخساير','Financials':'الحسابات','Overview':'نظرة عامة','Projects':'المشاريع','Forecast':'التوقعات','Reports':'التقارير','Payments':'الدفعات','Invoices':'الفواتير','Technicians':'الفنيين','Quotations':'المقايسات',
 'OWNER PORTAL':'لوحة المالك','OWNER ACCESS':'حساب المالك','MANAGEMENT PORTAL':'إدارة المشاريع','Hello, Lamiaa':'أهلاً يا لمياء','A clear view of your projects, from first plans to final details.':'تابعي مشاريعك وحساباتها، من أول التخطيط لحد آخر تفصيلة.',
 'Sunday, 06 September 2026':'الأحد، ٦ سبتمبر ٢٠٢٦','Sep':'سبتمبر','September':'سبتمبر','Apr':'أبريل','May':'مايو','Jun':'يونيو','Jul':'يوليو','Aug':'أغسطس','Oct':'أكتوبر','Jan':'يناير','Feb':'فبراير','Mar':'مارس','Nov':'نوفمبر','Dec':'ديسمبر',
 'Open Projects':'المشاريع المفتوحة','Active Technicians':'الفنيين الشغالين','Total Contract Value':'إجمالي قيمة التعاقدات','Collected':'المتحصل','Outstanding':'المتبقي عند العملاء','Cost to Date':'التكلفة لحد دلوقتي','Forecast Remaining Cost':'التكلفة المتوقعة للباقي','Forecast Profit':'الربح المتوقع','Across your portfolio':'في كل المشاريع','Assigned to open projects':'متوزعين على المشاريع المفتوحة','signed contracts':'تعاقدات موقعة','of contract value':'من قيمة التعاقدات','remaining client balance':'باقي حساب العميل','incurred operating cost':'تكاليف تشغيل مسجلة','estimated to complete':'متوقع لاستكمال الشغل','forecast margin':'هامش الربح المتوقع',
 'THE BIG PICTURE':'الصورة الكاملة','Financial breakdown':'تفاصيل الحسابات','Portfolio to date':'كل المشاريع لحد دلوقتي','collected':'اتحصل','Client payments collected':'دفعات العملاء اللي اتحصلت','Client payments pending':'دفعات العملاء المتبقية','Materials & procurement':'الخامات والمشتريات','Technicians & subcontractors':'الفنيين والمقاولين','Other operational costs':'مصاريف تشغيل تانية','Forecast total cost':'إجمالي التكلفة المتوقع','Forecast profit margin':'هامش الربح المتوقع',
 'LOOKING AHEAD':'الفترة الجاية','Cash forecast':'توقعات السيولة','Expected cash flow':'الحركة النقدية المتوقعة','This week':'الأسبوع ده','This month':'الشهر ده','Collections':'التحصيلات','Outgoings':'المدفوعات','Net movement':'صافي الحركة','Collections need close follow-up':'التحصيلات محتاجة متابعة','EGP 35,000 is overdue. A further EGP 20,000 is needed to release the next phase at Palm Residence.':'فيه ٣٥٬٠٠٠ جنيه متأخرين. ومحتاجين ٢٠٬٠٠٠ جنيه كمان عشان نبدأ المرحلة الجاية في بالم ريزيدنس.','Estimates based on planned milestones; monthly figures include this week.':'التقديرات حسب مراحل الشغل المخططة، وأرقام الشهر شاملة الأسبوع ده.',
 'CASH MOVEMENT':'الحركة النقدية','Collections & costs':'التحصيلات والتكاليف','Cost':'التكلفة','EGP thousands · September is forecast':'بالألف جنيه · سبتمبر أرقام متوقعة','CRAFTING EVERY DETAIL':'متابعة تفاصيل الشغل','Projects overview':'ملخص المشاريع','5 open projects · 8 active technicians':'٥ مشاريع مفتوحة · ٨ فنيين شغالين','Needs attention':'محتاج متابعة','PAYMENT OVERDUE':'دفعة متأخرة','COST RISK':'احتمال زيادة التكلفة','SCHEDULE DELAY':'تأخير في الشغل','Review project':'افتح المشروع','CLIENT BALANCES':'حسابات العملاء','Still to collect':'لسه هنتحصّله','Total outstanding':'إجمالي المتبقي','Considered design.':'تصميم مدروس.','Confident delivery.':'وتنفيذ تطمّن له.','Illustrative data':'بيانات تجريبية','Updated':'آخر تحديث','Replay brand introduction':'شغّل مقدمة اللوجو تاني',
 'The Courtyard Villa':'فيلا كورت يارد','Palm Residence':'بالم ريزيدنس','The West Duplex':'دوبلكس ويست','Garden Apartment':'شقة جاردن','Heliopolis Studio':'استوديو مصر الجديدة','New Cairo':'القاهرة الجديدة','Sheikh Zayed':'الشيخ زايد','6th of October':'٦ أكتوبر','Maadi':'المعادي','Heliopolis':'مصر الجديدة',
 'Project completion':'نسبة إنجاز المشروع','CURRENT PHASE':'المرحلة الحالية','NEXT PHASE':'المرحلة الجاية','Finishing & fixtures':'التشطيبات والتركيبات','Final inspection':'المعاينة النهائية','Electrical & plumbing':'الكهربا والسباكة','Plastering':'المحارة','Flooring':'الأرضيات','Painting':'الدهانات','Custom joinery':'شغل النجارة','Installation':'التركيب','Electrical work':'شغل الكهربا','On track':'ماشي حسب الخطة','Payment pending':'مستنيين دفعة','Cost risk':'احتمال زيادة التكلفة','Delayed':'متأخر',
 'Total contract value':'إجمالي التعاقد','Amount paid':'المدفوع من العميل','Still needed from customer':'المتبقي على العميل','Operational cost to date':'تكلفة التشغيل لحد دلوقتي','Next phase initial cost':'المطلوب لبدء المرحلة الجاية','Forecast final cost':'التكلفة النهائية المتوقعة','Forecast remaining cost':'التكلفة المتوقعة للباقي','Forecast profit':'الربح المتوقع','margin':'هامش ربح','View full details & schedule':'افتح التفاصيل والجدول','Close project details':'اقفل تفاصيل المشروع','Financial details':'تفاصيل الحسابات','Project schedule':'جدول المشروع','Illustrative phase dates · Snapshot 06 September 2026':'مواعيد تجريبية للمراحل · الوضع في ٦ سبتمبر ٢٠٢٦','Gantt chart':'جدول جانت','Complete':'خلصت','In progress':'شغالة','Planned':'مخططة','Blocked':'متوقفة','At risk':'محتاجة متابعة','NEXT ACTION':'الخطوة الجاية',
 'Design & approvals':'التصميم والاعتمادات','Site preparation':'تجهيز الموقع','Flooring & painting':'الأرضيات والدهانات','Fixtures & handover':'التركيبات والتسليم','Flooring & finishes':'الأرضيات والتشطيب','Inspection & handover':'المعاينة والتسليم','Site & services':'تجهيز الموقع والخدمات','Painting & fixtures':'الدهانات والتركيبات','Vertical gold line: 06 September · Dates are inclusive. Planned dates depend on prior phases and payment clearance.':'الخط الدهبي: ٦ سبتمبر. المواعيد شاملة يوم البداية والنهاية، ومرتبطة بإنهاء المراحل السابقة وتحصيل الدفعات.',
 'Confirm fixture delivery and prepare the final inspection checklist.':'أكّدوا ميعاد وصول التركيبات وجهّزوا قائمة المعاينة النهائية.','Confirm plastering materials and technician availability before the next phase.':'أكّدوا توافر خامات المحارة والفنيين قبل المرحلة الجاية.',
 'Send financial report':'جهّز تقرير حساب العميل','Send payment reminder':'جهّز تذكير بالدفعة','Financial report':'تقرير حساب العميل','Payment reminder':'تذكير بالدفعة','CLIENT COMMUNICATION':'مراسلات العملاء','Close message':'اقفل الرسالة','Message':'الرسالة','Copy message':'انسخ الرسالة','Download reminder':'نزّل التذكير','Download report sheet (CSV)':'نزّل كشف الحساب (CSV)','Client email':'إيميل العميل','Client WhatsApp number':'رقم واتساب العميل','Enter client email':'اكتب إيميل العميل','Country code + number, e.g. +20…':'اكتب الرقم بكود البلد، مثلاً ‎+20…','Open email draft':'افتح مسودة الإيميل','Open WhatsApp draft':'افتح مسودة واتساب','Review the message before sharing. No client contact details are saved. Opening a messaging app does not send the message.':'راجع الرسالة قبل ما تبعتها. بيانات التواصل مش محفوظة، وفتح الإيميل أو واتساب مش معناه إن الرسالة اتبعتت.',
 'Download requested. Nothing has been sent to the client.':'التنزيل بدأ. مفيش حاجة اتبعتت للعميل.','Message copied. Paste it into your client conversation.':'الرسالة اتنسخت. الصقها في محادثة العميل.','Select and copy the message manually.':'حدد الرسالة وانسخها بنفسك.','Enter a valid client email.':'اكتب إيميل صحيح للعميل.','Enter a complete international number with country code (8–15 digits).':'اكتب الرقم كامل بكود البلد، من ٨ لـ١٥ رقم.','Email draft requested in your mail app. No delivery has been confirmed.':'طلبنا فتح مسودة الإيميل. إرسال الرسالة لسه مش مؤكد.','WhatsApp draft requested. Review the recipient and press Send in WhatsApp. No delivery has been confirmed.':'طلبنا فتح واتساب. راجع الرقم واضغط إرسال من واتساب، الإرسال لسه مش مؤكد.',
 'PEOPLE & DELIVERY':'الفنيين والتنفيذ','Technician breakdown':'تفاصيل الفنيين','Active technicians':'الفنيين الشغالين','Incurred labour cost':'تكلفة العمالة المسجلة','Paid to technicians':'المدفوع للفنيين','Technician balance':'باقي حساب الفنيين','Technician assignments and payment breakdown':'توزيع الفنيين وتفاصيل دفعاتهم','Technician':'الفني','Trade':'التخصص','Project / phase':'المشروع / المرحلة','Incurred cost':'التكلفة المسجلة','Paid':'المدفوع','Balance':'الرصيد','Work status':'حالة الشغل','Finishing':'تشطيبات','Fixtures':'تركيبات','Electrical':'كهربا','Plumbing':'سباكة','Joinery':'نجارة','Awaiting phase release':'مستني بدء المرحلة','Quote review':'مراجعة عرض السعر',
 'Illustrative technician names and payments. Incurred labour costs reconcile to the portfolio’s technician and subcontractor total. Unpaid incurred costs are already included in cost to date.':'أسماء الفنيين والدفعات تجريبية. تكلفة العمالة متطابقة مع إجمالي تكلفة الفنيين والمقاولين، والمبالغ المستحقة اللي لسه ما اتدفعتش محسوبة بالفعل ضمن التكلفة.',
 'Apartment renovation · Demo':'تشطيب شقة · تجريبي','Swimming pool · Demo':'حمام سباحة · تجريبي','Apartment renovation':'تشطيب شقة','Swimming pool':'حمام سباحة','Demo Client A':'عميل تجريبي ١','Demo Client B':'عميل تجريبي ٢','Demo supplier':'مورد تجريبي','Demo subcontractor':'مقاول تجريبي','Company overhead':'مصاريف إدارية للشركة',
 'Project':'المشروع','All projects':'كل المشاريع','From':'من','Through':'لحد','Apply':'اعرض','Period':'الفترة','Custom / current':'الفترة اللي محددها','All activity to date':'كل الحركات لحد دلوقتي','Annual':'سنوي','Year':'السنة','First recorded activity':'أول حركة مسجلة','Latest recorded activity':'آخر حركة مسجلة','First activity':'أول حركة','Latest activity':'آخر حركة','The start date must be on or before the end date.':'تاريخ البداية لازم يكون قبل تاريخ النهاية أو نفس اليوم.',
 'Payments ledger':'سجل الدفعات','Client receipts and outgoing payments remain separate.':'دفعات العملاء والمدفوعات للموردين كل واحدة في سجل لوحدها.','Record payment':'سجّل دفعة','Record client receipt':'سجّل مبلغ مستلم من العميل','Record supplier / technician payment':'سجّل دفعة لمورد أو فني','Client receipts':'المستلم من العملاء','Supplier & technician payments':'مدفوعات الموردين والفنيين','Outgoing payments':'المدفوعات الخارجة','Net cash movement':'صافي الحركة النقدية','Download payment sheet':'نزّل كشف الدفعات','Transaction date':'تاريخ الحركة','Date':'التاريخ','Amount · EGP':'المبلغ بالجنيه','Description':'البيان','Received from':'مستلم من','Paid to':'مدفوع لـ','Payment method':'طريقة الدفع','Bank transfer':'تحويل بنكي','Cash':'كاش','Cheque':'شيك','Other':'أخرى','Receipt / payment reference':'رقم إيصال الاستلام أو الدفع','Counterparty':'الطرف التاني','Method / reference':'طريقة الدفع / رقم المرجع','Method':'طريقة الدفع','Reference':'المرجع','Client advance':'دفعة من العميل','Project advance':'دفعة مقدمة للمشروع','Materials payment':'دفعة خامات',
 'Payments affect the cash ledger. Record the related expense or earned revenue separately; saving a payment does not create either.':'الدفعة بتتسجل في الحركة النقدية. سجّل المصروف أو الإيراد المستحق بشكل منفصل، حفظ الدفعة مش بيضيفهم تلقائي.','This payment reference already exists. Use a unique reference.':'رقم الدفعة ده موجود قبل كده. استخدم رقم مختلف.','Enter an amount above zero and below 1 trillion EGP.':'اكتب مبلغ أكبر من صفر وأقل من تريليون جنيه.',
 'Save':'احفظ','Cancel':'إلغاء','Close':'اقفل','Saved on this browser.':'اتحفظ على المتصفح ده.','Could not save. Browser storage may be full.':'الحفظ ما تمش. ممكن مساحة المتصفح تكون مليانة.','Browser storage is unavailable. Open this demo in a standard browser window with local storage enabled.':'حفظ البيانات مش متاح. افتح النسخة في نافذة متصفح عادية وفعّل التخزين المحلي.',
 'Expenses & client charges':'المصروفات والمبالغ على العميل','Incurred costs and earned revenue drive the P&L. Client charges drive statements.':'الأرباح بتتحسب من الإيراد المستحق والتكلفة المسجلة. كشف العميل بيعرض المبالغ المحملة عليه.','Record expense':'سجّل مصروف','Record an incurred expense':'سجّل تكلفة على المشروع','Record client charge':'سجّل مبلغ على العميل','Record a client charge':'سجّل مبلغ على العميل','Incurred expenses':'المصروفات المسجلة','Client charges':'المبالغ المحملة على العميل','Cost category':'فئة المصروف','Materials':'خامات','Subcontractors':'مقاولين','Transport':'نقل','Design':'تصميم','Other direct costs':'تكاليف مباشرة تانية','Overhead':'مصاريف إدارية','Supplier / technician':'المورد / الفني','Invoice / expense reference':'رقم الفاتورة أو المصروف','Category':'الفئة','Cost · EGP':'التكلفة بالجنيه','Earned revenue included in this charge · EGP':'الإيراد المستحق من المبلغ ده بالجنيه','Charged · EGP':'المحمل على العميل بالجنيه','Earned revenue · EGP':'الإيراد المستحق بالجنيه',
 'This is an incurred cost, whether paid or unpaid. Record its cash payment in the payments ledger and save supporting documents in Invoices.':'دي تكلفة مسجلة، سواء اتدفعت أو لسه. سجّل الدفع في سجل الدفعات واحفظ المستند في الفواتير.','Enter earned revenue only for work or fees earned by this date. A client advance or unearned charge is not earned revenue. This demo does not infer accounting treatment from a quotation.':'اكتب الإيراد المستحق عن الشغل أو الأتعاب المستحقة لحد التاريخ ده بس. الدفعة المقدمة مش إيراد مستحق، والمقايسة لوحدها مش بتحدد المعالجة المحاسبية.','Earned revenue must be between zero and the charge amount.':'الإيراد المستحق لازم يكون من صفر لحد قيمة المبلغ المحمل على العميل.','This expense reference already exists.':'رقم المصروف ده موجود قبل كده.',
 'Illustrative renovation materials':'تكلفة تشطيب تجريبية','Completed works charged to client':'شغل منفذ ومحمّل على العميل','Illustrative supervision fee':'أتعاب إشراف · ١٥٪ من ٨٤٬٥٠٠','Engineering drawings':'رسومات هندسية','Completed civil milestone':'مرحلة أعمال مدنية منفذة','Civil work completed':'أعمال مدنية منفذة',
 'Invoice archive':'أرشيف الفواتير','Keep each supporting document with its project and expense.':'احفظ كل مستند مع المشروع والمصروف اللي يخصّه.','Save invoice':'احفظ فاتورة','Save an invoice / فاتورة':'احفظ فاتورة','Invoice date':'تاريخ الفاتورة','Invoice number':'رقم الفاتورة','Supplier / issuer':'المورد / مصدر الفاتورة','Invoice face value · EGP':'قيمة الفاتورة بالجنيه','Related expense':'المصروف المرتبط بالفاتورة','Document only — not linked':'مستند بس — مش مربوط بمصروف','Invoice file · PDF, JPG, PNG · up to 10 MB':'ملف الفاتورة · PDF أو صورة · لحد ١٠ ميجا','Saving an invoice stores the supporting document only. It does not post an expense or payment again.':'حفظ الفاتورة بيحفظ المستند بس، مش بيضيف المصروف أو الدفعة مرة تانية.','Choose a non-empty PDF, JPG or PNG no larger than 10 MB.':'اختار ملف PDF أو صورة JPG أو PNG، حجمه أكبر من صفر ولحد ١٠ ميجا.','The linked expense belongs to a different project.':'المصروف اللي اخترته تابع لمشروع تاني.','This invoice number is already saved for this issuer.':'رقم الفاتورة ده محفوظ قبل كده لنفس المورد.','No invoices saved yet. Add a PDF or photo to try the archive.':'لسه مفيش فواتير محفوظة. ضيف PDF أو صورة عشان تجرب الأرشيف.','Download invoice':'نزّل الفاتورة','Document only':'مستند بس','Linked to expense':'مربوط بالمصروف','The invoice file is not available on this browser.':'ملف الفاتورة مش موجود على المتصفح ده.',
 'Quotation builder · المقايسات':'تجهيز المقايسات','Build by reusable work blocks. Quantities, rates and fees calculate automatically.':'كوّن المقايسة من بنود جاهزة. الكميات والأسعار والأتعاب بتتحسب تلقائي.','New quotation':'مقايسة جديدة','REUSABLE BLOCK':'مجموعة بنود جاهزة','ITEMS':'بنود','Use block':'استخدم البنود','Saved quotations':'المقايسات المحفوظة','Quotation':'المقايسة','Status':'الحالة','Actions':'الإجراءات','Open':'افتح','Edit quotation':'عدّل المقايسة','Quotation reference':'رقم المقايسة','Quotation date':'تاريخ المقايسة','Draft':'مسودة','Sent':'اتبعتت','Approved':'معتمدة','Unit price · EGP':'سعر الوحدة بالجنيه','Line total':'إجمالي البند','Unit':'الوحدة','Quantity':'الكمية','Action':'الإجراء','Remove':'شيل البند','Add item':'ضيف بند','Save items as reusable block':'احفظ البنود للاستخدام تاني','Supervision fee · % of line subtotal':'نسبة الإشراف من إجمالي البنود %','Design fee · EGP':'أتعاب التصميم بالجنيه','Save quotation':'احفظ المقايسة','Download quotation sheet':'نزّل كشف المقايسة','Save reusable quotation block':'احفظ مجموعة بنود جاهزة','Block name':'اسم مجموعة البنود','Lump sum':'مقطوعية','Item':'قطعة','Pool · Civil works':'حمام سباحة · أعمال مدنية','Pool · Equipment':'حمام سباحة · المعدات','Renovation · Services':'تشطيبات · خدمات','Concrete works':'أعمال خرسانة','Waterproofing':'عزل','Mosaic finish':'تشطيب موزاييك','Sand filter':'فلتر رملي','Circulation pump':'طلمبة تدوير','Control panel':'لوحة تحكم','Electrical installation':'تأسيس كهربا','Plumbing installation':'تأسيس سباكة',
 'Select a block above to insert its items, or add your own. Rates are editable demo allowances. Marking a quote Approved does not post charges or revenue.':'اختار مجموعة من فوق عشان تضيف بنودها، أو ضيف بنودك بنفسك. الأسعار تجريبية وقابلة للتعديل. اعتماد المقايسة مش بيسجّل مبالغ على العميل أو إيراد تلقائي.','No automatic VAT calculation. These figures are a quotation, not a posted client balance or P&L revenue.':'ضريبة القيمة المضافة مش بتتحسب تلقائي. الأرقام دي عرض سعر، مش رصيد مسجل على العميل ولا إيراد في الأرباح.','Add at least one quotation item.':'ضيف بند واحد على الأقل للمقايسة.','Enter a valid quotation total above zero and below 1 trillion EGP.':'إجمالي المقايسة لازم يكون أكبر من صفر وأقل من تريليون جنيه.','This quotation reference already exists.':'رقم المقايسة ده موجود قبل كده.','Quotation saved. No client charge or revenue was posted.':'المقايسة اتحفظت. مفيش مبلغ اتحمّل على العميل أو إيراد اتسجل.',
 'Subtotal':'الإجمالي قبل الأتعاب','supervision':'الإشراف','design':'التصميم','Total EGP':'الإجمالي بالجنيه','Total · EGP':'الإجمالي بالجنيه',
 'Operating profit & loss':'الأرباح والخساير التشغيلية','Choose a project or all projects, then an annual or cumulative period.':'اختار مشروع أو كل المشاريع، وبعدين حدد السنة أو الفترة لحد دلوقتي.','Earned revenue':'الإيراد المستحق','Direct costs':'التكاليف المباشرة','Gross profit':'مجمل الربح','Operating profit':'الربح التشغيلي','Direct project costs':'تكاليف المشاريع المباشرة','Allocated overhead expenses':'المصاريف الإدارية المحملة','Operating profit before tax':'الربح التشغيلي قبل الضرايب','Download P&L sheet':'نزّل كشف الأرباح والخساير','Print / save PDF':'اطبع / احفظ PDF',
 'Based on recorded earned revenue and incurred expenses in the selected period. Client receipts, outgoing payments, draft quotations and archived invoice files do not create additional profit or costs. No tax, depreciation, financing or unrecorded overhead entries are calculated automatically.':'الحساب حسب الإيراد المستحق والمصروفات المسجلة خلال الفترة. دفعات العملاء والمدفوعات والمقايسات والفواتير المحفوظة مش بتضيف ربح أو تكلفة تانية. الضرايب والإهلاك والتمويل والمصاريف غير المسجلة مش بتتحسب تلقائي.',
 'Client statement · كشف حساب العميل':'كشف حساب العميل','A dated record of charges, receipts, and the running account balance.':'كشف بالتواريخ للمبالغ المحملة على العميل ودفعاته ورصيد حسابه.','Opening balance':'الرصيد أول الفترة','Entry':'نوع الحركة','Charges':'المبالغ على العميل','Receipts':'المستلم','Client credit balance':'رصيد دائن للعميل','Balance to collect':'المطلوب من العميل','Download statement sheet':'نزّل كشف الحساب','Prepare email / WhatsApp':'جهّز إيميل / واتساب','Share client statement':'جهّز مشاركة كشف العميل','WhatsApp number including country code':'رقم واتساب بكود البلد','Open draft in':'افتح المسودة في','Email':'الإيميل','WhatsApp':'واتساب','Open draft':'افتح المسودة','A positive balance is charged but unpaid; a negative balance is credit held for the client. This is an account balance, not an overdue assessment. Internal costs and profit are excluded.':'الرصيد الموجب مبلغ على العميل لسه ما اتدفعش، والسالب رصيد دائن ليه. ده رصيد حساب مش تقييم للتأخير. التكاليف الداخلية والربح مش ظاهرين للعميل.',
 'Download the statement first and attach it manually in your messaging app. Contact details are not stored. You will press Send in that app.':'نزّل الكشف الأول وارفقه بنفسك في الإيميل أو واتساب. بيانات التواصل مش بتتحفظ، وإنت اللي هتضغط إرسال من التطبيق.','Draft requested in your messaging app. Nothing has been confirmed as sent.':'طلبنا فتح مسودة في تطبيق المراسلة. الإرسال لسه مش مؤكد.','Enter an international WhatsApp number with country code.':'اكتب رقم واتساب كامل بكود البلد.','Report downloaded. No message has been sent.':'التقرير اتنزّل. مفيش رسالة اتبعتت.',
 'PROJECT FINANCIALS':'حسابات المشاريع','One project. The complete picture.':'كل تفاصيل المشروع في مكان واحد.','Open a project to inspect its statement, supporting documents and quotation blocks.':'افتح المشروع عشان تراجع حسابه ومستنداته وبنود مقايساته.','Recorded project costs':'تكاليف المشاريع المسجلة','Charges to clients':'المبالغ المحملة على العملاء','Net client account balance':'صافي أرصدة العملاء','Client credit':'رصيد دائن للعميل','Account settled':'الحساب متسوي','Renovation & supervision':'تشطيبات وإشراف','Pool construction':'إنشاء حمام سباحة','Receipts against recorded charges':'المستلم مقارنة بالمبالغ على العميل','Charged to client':'المحمل على العميل','Payments received':'الدفعات المستلمة','Recorded costs':'التكاليف المسجلة','Open complete project file':'افتح ملف المشروع بالكامل','01 / Review the overview':'١ / راجع الملخص','02 / Open the project file':'٢ / افتح ملف المشروع','03 / Record, document, report':'٣ / سجّل وارفق المستند واطلع التقرير','Add Client Receipt':'ضيف مبلغ من العميل','Add Expense':'ضيف مصروف',
 'PROJECT FINANCIAL FILE':'ملف حسابات المشروع','Expense statement':'كشف المصروفات','FINANCIAL POSITION':'موقف الحساب','From costs to client balance':'من المصروفات لحد رصيد العميل','Recorded project expenses':'مصروفات المشروع المسجلة','Additional client charges above costs':'مبالغ على العميل زيادة عن التكلفة','Total charged to client':'إجمالي المحمل على العميل','Less: client receipts':'ناقص: دفعات العميل','Closing client credit':'رصيد العميل الدائن في الآخر','Closing balance to collect':'المتبقي المطلوب من العميل','COST COMPOSITION':'توزيع التكلفة','Where the money goes':'المصاريف رايحة فين','Cash received':'الكاش المستلم','Cash paid out':'الكاش المدفوع','Net recorded cash movement':'صافي حركة الكاش المسجلة','Operating profit to date':'الربح التشغيلي لحد دلوقتي','Client receipt':'دفعة من العميل','Expense':'مصروف','Create quotation from blocks':'جهّز مقايسة من البنود','Review notes':'ملاحظات للمراجعة','The difference between charges and costs can include fees and billing timing. It is not automatically a profit calculation.':'فرق المبالغ المحملة والتكاليف ممكن يشمل أتعاب أو فرق توقيت الفوترة. مش بالضرورة يكون هو الربح.',
 'DETAILED PROJECT ACCOUNT':'تفاصيل حساب المشروع','Expense statement · كشف المصروفات':'كشف مصروفات المشروع','Line-by-line expenditure, service fees, receipts and the client account.':'المصروفات بند بند، والأتعاب، والمستلم، وحساب العميل.','Download detailed sheet':'نزّل الكشف التفصيلي','Money received from the client':'المبالغ اللي استلمناها من العميل','Expenses':'المصروفات','Detailed cost categories and supporting references':'تفاصيل فئات المصاريف وأرقام المستندات','No.':'م','Supplier / reference':'المورد / المرجع','Record status':'حالة التسجيل','Demo cost breakdown':'تفصيل تجريبي','Recorded':'مسجل','Client charges & fees':'المبالغ والأتعاب على العميل','Charges actually posted to the client account':'المبالغ اللي اتسجلت فعلاً على حساب العميل','Charge / service':'البند / الخدمة','Total charged':'إجمالي المحمل','Less received':'ناقص المستلم','Record receipt':'سجّل مبلغ مستلم','Client-facing statement & sharing':'كشف العميل ومشاركته','CASH LEDGER':'سجل الكاش','Every receipt and payment':'كل مبلغ مستلم أو مدفوع','Receipts and outgoing payments stay in separate records.':'المبالغ المستلمة والمدفوعة كل واحدة في سجل لوحدها.','Payment reference':'رقم الدفعة','Download receipts sheet':'نزّل كشف المستلم','Download outgoing sheet':'نزّل كشف المدفوعات',
 'SUPPORTING DOCUMENTS':'المستندات المؤيدة','Invoices & receipts':'الفواتير والإيصالات','Documents saved under this project only.':'المستندات المحفوظة للمشروع ده بس.','Download original':'نزّل أصل المستند','DOCUMENT ARCHIVE':'أرشيف المستندات','A place for every invoice.':'كل فاتورة ليها مكان.','Save supplier invoices, material receipts and technician documents as PDF, JPG or PNG. Link them to a recorded expense to keep the project file traceable.':'احفظ فواتير الموردين وإيصالات الخامات ومستندات الفنيين PDF أو صور. اربط المستند بالمصروف عشان تقدر ترجعله بسهولة.','Save the first invoice':'احفظ أول فاتورة','BUILD THE SCOPE, BLOCK BY BLOCK':'كوّن المقايسة بند بند','Quotation blocks · بنود المقايسة':'بنود المقايسة الجاهزة','Start with a work package, then refine quantities, rates and fees.':'ابدأ بمجموعة بنود، وبعدين ظبّط الكميات والأسعار والأتعاب.','LINE ITEMS':'بنود','Build quotation with this block':'ابدأ المقايسة بالبنود دي','Project quotations':'مقايسات المشروع','Open quotation':'افتح المقايسة','A quotation total is not a cost, a receipt or earned revenue. Approval does not automatically post financial entries.':'إجمالي المقايسة مش تكلفة أو دفعة أو إيراد مستحق. الاعتماد مش بيسجّل حركات مالية تلقائي.','PROJECT PERFORMANCE':'أداء المشروع','All recorded activity through':'كل الحركات المسجلة لحد','Choose reporting period / export':'حدد فترة التقرير / نزّل التقرير','Allocated overhead':'مصاريف إدارية محملة','How this report is calculated':'التقرير ده بيتحسب إزاي',
 'Reports centre':'مركز التقارير','18 reports from the records saved in this financial workspace.':'١٨ تقرير من البيانات المحفوظة في حسابات المشاريع.','Download report sheet':'نزّل كشف التقرير','Reports that need more accounting records':'تقارير محتاجة بيانات محاسبية أكتر','Balance sheet, trial balance and general ledger need a chart of accounts, opening balances and balanced journal entries. Aging reports need due dates and invoice-level payment allocations. Tax reports need confirmed tax codes and jurisdiction. Budget variance needs approved cost budgets. These are not included in the 18 reports above.':'الميزانية وميزان المراجعة ودفتر الأستاذ محتاجين دليل حسابات وأرصدة افتتاحية وقيود متوازنة. تقارير أعمار الديون محتاجة مواعيد استحقاق وربط الدفعات بالفواتير. تقارير الضرايب محتاجة أكواد وقواعد ضريبية مؤكدة، ومقارنة الميزانية محتاجة موازنة تكلفة معتمدة. دول مش ضمن الـ١٨ تقرير.',
 'Profitability':'الربحية','Costs':'التكاليف','Clients':'العملاء','Documents':'المستندات','Monthly profit & loss':'الأرباح والخساير بالشهر','Project profitability':'ربحية كل مشروع','Revenue by project':'الإيراد حسب المشروع','Expenses by category':'المصاريف حسب الفئة','Expenses by supplier / technician':'المصاريف حسب المورد أو الفني','Detailed expense register':'سجل المصروفات التفصيلي','Client receipt register':'سجل المستلم من العملاء','Supplier & technician payment register':'سجل مدفوعات الموردين والفنيين','Cash movement register':'سجل حركة الكاش','Monthly cash movements':'حركة الكاش بالشهر','Client balance summary':'ملخص أرصدة العملاء','Client statement detail':'كشف حساب العميل التفصيلي','Client charge register':'سجل المبالغ على العملاء','Charges and earned revenue':'المبالغ المحملة والإيراد المستحق','Quotation register':'سجل المقايسات','Invoice document register':'سجل مستندات الفواتير','Expenses without linked invoices':'مصاريف من غير فواتير مربوطة',
 'Recorded earned revenue less incurred costs; before tax.':'الإيراد المستحق المسجل ناقص التكاليف المسجلة، قبل الضرايب.','Revenue, direct costs, overhead and profit for each active month.':'الإيراد والتكاليف المباشرة والإدارية والربح لكل شهر فيه حركة.','Compare project revenue, costs and operating margins.':'قارن الإيرادات والتكاليف وهوامش الربح بين المشاريع.','Earned revenue, independently of client cash receipts.':'الإيراد المستحق، بشكل منفصل عن تحصيلات العملاء.','Group incurred costs by their recorded category.':'تجميع التكاليف حسب الفئة المسجلة.','Group incurred costs by the recorded counterparty name.':'تجميع التكاليف حسب اسم المورد أو الفني المسجل.','Every recorded expense and its supporting reference.':'كل مصروف مسجل والمرجع بتاعه.','Dated client receipts and payment references.':'دفعات العملاء بالتواريخ وأرقام المراجع.','Dated outgoing cash payments; not an expense recognition report.':'المدفوعات النقدية بالتواريخ، مش تقرير إثبات مصروف.','Cash receipts and outgoings with opening and running net movement.':'المستلم والمدفوع وصافي الحركة أول الفترة وخلالها.','Cash received, paid and net movement by active month.':'المستلم والمدفوع وصافي الحركة لكل شهر فيه بيانات.','Charges less receipts through the end date, including earlier activity.':'المبالغ المحملة ناقص المستلم لحد نهاية الفترة، شاملة الحركات الأقدم.','Opening balances, charges, receipts and running client balances.':'رصيد أول الفترة والمبالغ المحملة والمستلم والرصيد المتحرك.','All posted client charges, including earned portions.':'كل المبالغ المسجلة على العملاء، ومنها الجزء المستحق كإيراد.','Compare client charges with their recorded earned portions.':'قارن المبالغ على العميل بالجزء المستحق كإيراد.','Saved quotations and their current statuses; not posted revenue.':'المقايسات المحفوظة وحالتها الحالية، مش إيراد مسجل.','Archived invoice metadata; values are not additional expenses.':'بيانات الفواتير المحفوظة، وقيمتها مش مصاريف إضافية.','Recorded expenses with no linked invoice document.':'المصاريف اللي مفيش مستند فاتورة مربوط بيها.',
 'Grouped by exact recorded name; duplicate names are not automatically merged.':'التجميع حسب الاسم المسجل بالظبط، والأسماء المكررة مش بتتدمج تلقائي.','Checks documents linked now, even if uploaded after the report period; does not establish invoice validity.':'بيفحص المستندات المربوطة حاليًا حتى لو اترفعت بعد الفترة، ومش بيأكد صحة الفاتورة.','This is not a bank balance or a statutory cash flow statement; opening cash balances are not recorded.':'ده مش رصيد بنك ولا قائمة تدفقات نقدية قانونية، والأرصدة النقدية الافتتاحية مش مسجلة.','The start date is intentionally ignored. This is not an overdue/aging assessment.':'تاريخ البداية مش مستخدم هنا عشان يظهر الرصيد كله. ده مش تقرير تأخير أو أعمار ديون.','Running balance resets per project. Positive is unpaid charges; negative is client credit. Internal costs are excluded.':'الرصيد بيتحسب لكل مشروع لوحده. الموجب مستحق على العميل، والسالب رصيد دائن ليه. التكاليف الداخلية مش ظاهرة.','This is a charge reconciliation, not a deferred-revenue liability balance.':'دي مقارنة بين المبالغ والإيراد، مش رصيد التزام للإيراد المؤجل.','Filtered by quotation date; status history and budget baselines are not stored.':'الفلترة بتاريخ المقايسة. تاريخ تغيّر الحالة وخط أساس الموازنة مش محفوظين.',
 'Month':'الشهر','Overheads':'المصاريف الإدارية','Operating margin %':'هامش الربح التشغيلي %','Incurred expenses · EGP':'المصاريف المسجلة بالجنيه','Incurred cost · EGP':'التكلفة المسجلة بالجنيه','Cumulative net movement':'صافي الحركة المتراكم','Opening':'أول الفترة','Prior activity':'الحركات السابقة','Net recorded movement before period':'صافي الحركة المسجلة قبل الفترة','Client':'العميل','Charges to date':'المحمل لحد دلوقتي','Receipts to date':'المستلم لحد دلوقتي','Client balance':'رصيد العميل','Earned · EGP':'المستحق كإيراد بالجنيه','Recorded earned revenue':'الإيراد المستحق المسجل','Unearned portion of charges':'الجزء اللي لسه مش مستحق كإيراد','Current status':'الحالة الحالية','Line subtotal':'إجمالي البنود','Supervision fee':'أتعاب الإشراف','Design fee':'أتعاب التصميم','Invoice no.':'رقم الفاتورة','Issuer':'مصدر الفاتورة','Filename':'اسم الملف','Expense reference':'مرجع المصروف','Face value · EGP':'قيمة الفاتورة بالجنيه','Not linked':'مش مربوط','Not recorded':'مش مسجل','No records match this selection.':'مفيش بيانات مطابقة للاختيار ده.','EGP unless stated':'بالجنيه إلا لو مكتوب غير كده','EGP':'ج.م','technicians':'فنيين','technician':'فني','active':'شغال','complete':'خلص','project files':'ملفات مشاريع','expense lines':'بنود مصروفات','payments':'دفعات','invoices':'فواتير','quotations':'مقايسات','DEMO':'تجريبي','Demo':'تجريبي','FILE':'ملف',
 'Financial entry details':'تفاصيل الحركة المالية','Received · EGP':'المستلم بالجنيه','Expense · EGP':'المصروف بالجنيه','Illustrative breakdown of the existing aggregate cost':'تفصيل تجريبي للتكلفة المجمعة المسجلة','Charge':'مبلغ على العميل','Receipt':'دفعة مستلمة','Amount':'المبلغ','Currency':'العملة','Basis':'أساس الحساب','Note':'ملاحظة','Line':'البند','Account':'الحساب'
};
Object.assign(phrases,{
 'EGP 35,000 overdue by 7 days. Collection is needed before painting starts.':'٣٥٬٠٠٠ جنيه متأخرين ٧ أيام. محتاجين التحصيل قبل بدء الدهانات.',
 'Joinery quote is EGP 12,000 above the phase allowance. Confirm the scope before approval.':'عرض النجارة أعلى من مخصص المرحلة بـ١٢٬٠٠٠ جنيه. راجع البنود قبل الاعتماد.',
 'Electrical work is 5 days behind. Confirm the technician’s revised completion date.':'شغل الكهربا متأخر ٥ أيام. أكّد ميعاد التسليم الجديد مع الفني.',
 'EGP 35,000 is overdue by 7 days. Available project cash is EGP 50,000 against EGP 70,000 needed for painting: collect at least EGP 20,000 to release the phase.':'٣٥٬٠٠٠ جنيه متأخرين ٧ أيام. المتاح ٥٠٬٠٠٠ جنيه والدهانات محتاجة ٧٠٬٠٠٠، لازم نحصّل ٢٠٬٠٠٠ جنيه على الأقل عشان نبدأ.',
 'Joinery quote exceeds the phase allowance by EGP 12,000. Review scope and approve the quote before installation. The current forecast includes this estimate.':'عرض النجارة أعلى من المخصص بـ١٢٬٠٠٠ جنيه. راجع الشغل واعتمد العرض قبل التركيب. التوقع الحالي شامل التقدير ده.',
 'Electrical work is 5 days behind the original 06 September finish. The schedule shows a provisional revised finish of 11 September; confirm with the technician.':'شغل الكهربا متأخر ٥ أيام عن ميعاده الأصلي، ٦ سبتمبر. الميعاد الجديد المبدئي ١١ سبتمبر؛ أكّده مع الفني.',
 'Verify the overdue installment against your records.':'راجع الدفعة المتأخرة مع سجلاتك.',
 'The sheet includes client-facing balances only; internal costs and profit are excluded. CSV opens in Excel or Google Sheets.':'الكشف فيه حساب العميل بس، من غير التكاليف الداخلية والربح. ملف CSV بيفتح في Excel أو Google Sheets.',
 'Review the recipient and message, then send from your chosen app.':'راجع الرقم أو الإيميل والرسالة، وبعدها ابعتها من التطبيق اللي اخترته.',
 'The balance summary is included in the message. Download the CSV sheet above and attach it in email or WhatsApp before sending.':'ملخص الحساب موجود في الرسالة. نزّل الكشف من فوق وارفقه في الإيميل أو واتساب قبل الإرسال.',
 'Contact details are used for this draft only and are not saved.':'بيانات التواصل للمسودة دي بس ومش بتتحفظ.',
 'The sample cost breakdown follows the expense-sheet categories. Supervision and drawings are listed separately in the statement. Returns, refunds and missing transport charges need their own confirmed records before they change totals.':'تفاصيل المصاريف التجريبية حسب فئات الكشف. الإشراف والرسومات منفصلين، والمرتجعات والمبالغ المردودة والنقل الناقص لازم يتسجلوا ويتأكدوا قبل تغيير الإجمالي.',
 'Quotation blocks remain separate from actual costs. Confirm the quantities, supplier prices and approval status before posting any client charge.':'بنود المقايسة منفصلة عن التكلفة الفعلية. راجع الكميات وأسعار الموردين والاعتماد قبل تحميل أي مبلغ على العميل.',
 'Invoices saved:':'عدد الفواتير المحفوظة:',
 'Payments without document matching remain unverified; this demo does not reconcile bank transactions automatically.':'الدفعات اللي مش متطابقة مع مستندات لسه محتاجة مراجعة. النسخة دي مش بتطابق حركات البنك تلقائي.',
 'The 11 sample breakdown lines total the existing EGP 84,500 expense record; they are not added on top of it. Dates and supplier details are demo fields, not extracted invoice evidence.':'الـ١١ بند التجريبيين مجموعهم ٨٤٬٥٠٠ جنيه، نفس المصروف المسجل مش زيادة عليه. التواريخ وبيانات الموردين تجريبية ومش إثبات من فواتير.',
 'Earned revenue is explicitly recorded against client charges. Incurred expenses count when recorded, whether paid or unpaid. Client advances, quotations and invoice attachments do not create profit. Taxes, financing and unrecorded costs are excluded.':'الإيراد المستحق بيتسجل بشكل صريح مع المبالغ على العميل. المصروفات بتتحسب وقت تسجيلها، اتدفعت أو لسه. دفعات العملاء المقدمة والمقايسات والفواتير المرفقة مش بتخلق ربح. الضرايب والتمويل والتكاليف غير المسجلة مش محسوبين.',
 'Project financial file':'ملف حسابات المشروع','Close project financial file':'اقفل ملف حسابات المشروع','Project financial sections':'أقسام حساب المشروع','Statement':'كشف الحساب','SAMPLE CLIENT STATEMENT':'كشف عميل تجريبي','DEMO REPORT':'تقرير تجريبي','FINANCIAL REPORT':'تقرير مالي','CLIENT FINANCIAL REPORT':'كشف حساب العميل','PAYMENT SHEET':'كشف الدفعات','CLIENT STATEMENT':'كشف العميل','OPERATING P&L':'الأرباح والخساير التشغيلية','DETAILED PROJECT STATEMENT':'كشف مشروع تفصيلي','PROJECT FINANCIAL SHEET':'كشف حساب المشروع','QUOTATION':'مقايسة',
 'Hello ':'أهلاً ', 'Please find your Trust M statement for ':'ده كشف حسابك من Trust M لمشروع ', 'through ':'لحد ', 'Opening balance:':'رصيد أول الفترة:', 'Charges in period:':'المبالغ المحملة في الفترة:', 'Receipts in period:':'المستلم خلال الفترة:', 'Closing ':'الرصيد في الآخر: ', 'Thank you,':'شكرًا،', 'Sample statement — review before sending.':'كشف تجريبي — راجعه قبل الإرسال.', 'balance':'رصيد', 'credit':'دائن',
 'Total expenses':'إجمالي المصروفات','Client account balance':'رصيد حساب العميل','All recorded activity':'كل الحركات المسجلة','Total costs':'إجمالي التكاليف','Client charge date':'تاريخ المبلغ المحمل','Charges EGP':'المحمل بالجنيه','Receipts EGP':'المستلم بالجنيه','Balance EGP':'الرصيد بالجنيه','Closing EGP':'الرصيد النهائي بالجنيه','Opening EGP':'رصيد أول الفترة بالجنيه','Expense date':'تاريخ المصروف','As of':'لحد تاريخ','Contract value':'قيمة التعاقد','Remaining contract balance':'باقي قيمة التعاقد','Overdue installment':'الدفعة المتأخرة','Overdue due date':'تاريخ استحقاق الدفعة المتأخرة',
 'Remaining contract balance is not necessarily due now. Future installments follow agreed milestones.':'مش شرط باقي قيمة التعاقد كله يكون مستحق دلوقتي. الدفعات الجاية حسب المراحل المتفق عليها.',
 'Foundation plumbing purchases':'مشتريات سباكة تأسيس','Concealed plumbing purchases':'مشتريات دفن','Material transport':'نقل خامات','First-fix electrical purchases':'مشتريات كهربا تأسيس','Tile purchases':'مشتريات سيراميك','Roof tiles & marble removal':'تكسير بلاط السطح والرخام','Tile handling & storage':'تشوين السيراميك','Sand relocation':'نقل رملة من السطح','Debris removal':'جمع المخلفات','Waterproofing test':'اختبار العزل','Ceramics':'سيراميك','Demolition':'تكسير','Site logistics':'تشوينات'
});
Object.assign(phrases,{
 'PHASE':'المرحلة','PROJECT':'المشروع','FORECAST':'التوقعات','Total':'الإجمالي','Profit':'الربح','Current phase':'المرحلة الحالية','Next phase':'المرحلة الجاية','Linked to':'مربوط بـ','All activity':'كل الحركات',
 'إضافة مبلغ مستلم':'ضيف مبلغ مستلم','إضافة مصروف':'ضيف مصروف','إضافة مبلغ من العميل':'ضيف مبلغ من العميل','تنزيل كشف الحساب':'نزّل كشف الحساب','حفظ الملاحظة':'احفظ الملاحظة','ملاحظة جديدة':'ضيف ملاحظة','لا توجد ملاحظات محفوظة لهذا المشروع.':'لسه مفيش ملاحظات محفوظة للمشروع ده.','لا توجد دفعات مستلمة بعد':'لسه مفيش دفعات مستلمة','لا توجد مصروفات مسجلة بعد':'لسه مفيش مصروفات مسجلة','ملاحظات للمراجعة فقط — لا تغيّر الإجمالي حتى تسجيل التسوية المالية.':'دي ملاحظات للمراجعة بس، مش بتغيّر الإجمالي غير لما تسجّل التسوية المالية.','اضغط على البيان لعرض التفاصيل.':'اضغط على البيان عشان تشوف التفاصيل.','تم حفظ الملاحظة دون تغيير الأرصدة.':'الملاحظة اتحفظت من غير ما تغيّر الأرصدة.','تعذر الحفظ. حاول مرة أخرى.':'الحفظ ما تمش، جرّب تاني.',
 'أمثلة من الملف المرجعي: مرتجع كرتونتي سيراميك، مراجعة رد ١٬٠٠٠ جنيه حجز السيراميك، وقيمة نقل السيراميك. هذه أمثلة وليست تسويات مسجلة في المشروع التجريبي.':'أمثلة من ملفك: مرتجع كرتونتين سيراميك، مراجعة رد ١٬٠٠٠ جنيه حجز السيراميك، وتكلفة نقل السيراميك. دي أمثلة، مش تسويات مسجلة في المشروع التجريبي.',
 'The remaining contract balance is not necessarily due now. Future installments follow the agreed contract milestones.':'مش شرط باقي التعاقد كله يكون مستحق دلوقتي. الدفعات الجاية حسب المراحل المتفق عليها.',
 'No automatic VAT calculation; this document does not post client charges or earned revenue.':'ضريبة القيمة المضافة مش بتتحسب تلقائي. المستند ده مش بيسجّل مبالغ على العميل أو إيراد مستحق.',
 'Recorded earned revenue less incurred expenses. Excludes unrecorded costs, automatic taxes, depreciation and financing.':'الإيراد المستحق المسجل ناقص المصروفات. من غير التكاليف غير المسجلة أو حساب تلقائي للضرايب والإهلاك والتمويل.',
 'Positive balance is unpaid charges; negative balance is client credit. Not an overdue assessment.':'الرصيد الموجب مبالغ على العميل والسالب رصيد دائن ليه. ده مش تقييم لتأخر السداد.',
 'Internal owner statement. Detailed sample lines replace the sample aggregate for presentation only; do not add both.':'كشف داخلي للمالك. البنود التفصيلية بدل الإجمالي التجريبي للعرض بس، ما تجمعهمش مع بعض.',
 'All recorded activity. Running balance is receipts less incurred expenses, not a bank balance.':'كل الحركات المسجلة. الرصيد المتحرك هو المستلم ناقص المصروفات المسجلة، مش رصيد بنك.'
});
const keys=Object.keys(phrases).sort((a,b)=>b.length-a.length);
function translate(value){let s=String(value);if(phrases[s])return phrases[s];for(const k of keys){if(k.length<4||!s.includes(k))continue;s=s.split(k).join(phrases[k]);}return s.replace(/\bEGP\b/g,'ج.م').replace(/\bP&L\b/g,'الأرباح والخساير').replace(/\b(Apr|May|Jun|Jul|Aug|Sep|Oct|Jan|Feb|Mar|Nov|Dec)\b/g,k=>phrases[k]);}
window.egText=translate;
function visit(node){
 if(node.nodeType===Node.TEXT_NODE){if(node.parentElement?.closest('script,style,[data-no-translate]'))return;const old=node.nodeValue;if(!old.trim())return;const option=node.parentElement?.closest('option');if(option&&!option.hasAttribute('value'))option.setAttribute('value',option.value);const next=translate(old);if(next!==old)node.nodeValue=next;return;}
 if(node.nodeType!==Node.ELEMENT_NODE&&node.nodeType!==Node.DOCUMENT_NODE)return;
 if(node.matches?.('script,style,[data-no-translate]'))return;
 for(const attr of ['placeholder','aria-label','title']){if(node.hasAttribute?.(attr)){const old=node.getAttribute(attr),next=translate(old);if(next!==old)node.setAttribute(attr,next);}}
 if(node.tagName==='TEXTAREA'&&(node.id==='client-message'||node.name==='message')){const next=translate(node.value);if(next!==node.value)node.value=next;}
 for(const child of [...node.childNodes])visit(child);
 if(node.matches?.('table.finance-table')){const labels=[...node.querySelectorAll('thead th')].map(cell=>cell.textContent.trim());node.querySelectorAll('tbody tr').forEach(row=>[...row.children].forEach((cell,index)=>cell.dataset.label=labels[index]||''));}
}
document.documentElement.lang='ar-EG';document.documentElement.dir='rtl';
visit(document.documentElement);
const observer=new MutationObserver(records=>{observer.disconnect();for(const r of records){if(r.type==='childList')r.addedNodes.forEach(visit);else visit(r.target);}observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['placeholder','aria-label','title']});});
observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['placeholder','aria-label','title']});
})();
