(async function(){
 'use strict';
 const profile=await window.TrustAuth.ready;if(window.TrustAuth.enabled&&!profile)return;
 const Store=TrustFinanceStore,M=FinanceModel,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>Number(v).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2}),categories=['إيجار عربية','إيجار مكتب','كهرباء','مياه','إنترنت وتليفون','بنزين ومواصلات','صيانة','مستلزمات مكتب','مرتبات إدارية','مصروف تشغيل تاني'];
 const today=new Date().toLocaleDateString('en-CA'),section=document.querySelector('#operations'),readOnly=/amr\.html$/i.test(location.pathname);let db,month='',busy=false;
 const dialog=document.createElement('dialog');dialog.className='project-dialog';dialog.setAttribute('aria-labelledby','operations-title');document.body.append(dialog);
 async function loadData(){if(readOnly&&Store.mode==='supabase'){const {data,error}=await TrustAuth.client.rpc('get_amr_operational_workspace');if(error)throw error;return data;}return Store.update(()=>{});}
 try{db=await loadData();}catch{section.innerHTML='<p>مش قادرين نفتح سجلات التشغيل دلوقتي.</p>';return;}
 const all=()=>db.expenses.filter(e=>e.project==='company-overhead');
 const paid=e=>M.sum(db.payments.filter(p=>p.linkedExpense===e.id&&p.direction==='out'),p=>p.amount);
 function draw(){const rows=all().filter(e=>!month||e.date.startsWith(month)),total=M.sum(rows,e=>e.amount),settled=M.sum(rows,paid),cash=M.sum(db.payments.filter(p=>p.project==='company-overhead'&&p.direction==='out'&&(!month||p.date.startsWith(month))),p=>p.amount);
 section.innerHTML=`<div class="section-top"><div><div class="eyebrow">حسابات الشركة</div><h2>مصروفات التشغيل</h2><p class="finance-note">سجلات فعلية بتبدأ من غير أرقام تجريبية. بتدخل في مصروفات الشركة، ومش بتتحمل على عميل تلقائي.</p></div>${readOnly?'':'<a class="quiet-button" href="finance.html">افتح الحسابات والتقارير</a>'}</div><div class="filter-row"><label>شهر المصروف<input type="month" id="operations-month" value="${month}"></label><button id="operations-all" class="quiet-button">كل الشهور</button><button id="operations-refresh" class="quiet-button">حدّث</button>${readOnly?'':'<button id="add-operation" class="gold-button">+ ضيف مصروف تشغيل</button>'}<button id="export-operations" class="quiet-button">نزّل الكشف</button></div><div class="finance-kpis">${[['مصروفات الفترة',total],['المسدد على المصروفات دي',settled],['لسه مطلوب سداد',M.money(total-settled)],['المدفوع نقديًا في الفترة',cash]].map(([label,n])=>`<div class="kpi"><span>${label}</span><strong>${money(n)}</strong><small>جنيه مصري</small></div>`).join('')}</div><div class="finance-table-wrap"><table class="finance-table"><thead><tr>${['تاريخ المصروف','البند','البيان / المستفيد','القيمة','المسدد','الباقي','الفواتير والإيصالات',''].map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(e=>`<tr><td>${esc(e.date)}</td><td>${esc(e.operatingCategory)}</td><td>${esc(e.description)}<small>${esc(e.party)} · ${esc(e.reference)}</small></td><td>${money(e.amount)}</td><td>${money(paid(e))}</td><td>${money(M.money(e.amount-paid(e)))}</td><td>${db.payments.filter(p=>p.linkedExpense===e.id&&p.voucher).map(p=>`<button data-operation-receipt="${esc(p.id)}">${esc(p.voucher.number)}</button>`).join('<br>')}${db.invoices.filter(i=>i.linked===e.id).map(i=>`<button data-operation-file="${esc(i.id)}">الفاتورة</button>`).join('')}</td><td>${readOnly?paid(e)<e.amount?'غير مسدد':'متسدد':paid(e)<e.amount?`<button data-settle="${esc(e.id)}">سجّل سداد</button>`:'متسدد'}</td></tr>`).join(''):'<tr><td colspan="8">لسه مفيش مصروفات تشغيل مسجلة للفترة دي.</td></tr>'}</tbody></table></div><p class="finance-note">المسدد محسوب من الدفعات المرتبطة بالمصروف، حتى لو اتدفعت في شهر تاني. المدفوع نقديًا حسب تاريخ الدفع. المصروف بيتحسب مرة واحدة في الأرباح والخساير.</p><p id="operations-status" role="status"></p>`;
 document.querySelector('#operations-month').onchange=e=>{month=e.target.value;draw();};document.querySelector('#operations-all').onclick=()=>{month='';draw();};document.querySelector('#operations-refresh').onclick=async()=>{db=await loadData()||db;draw();};if(!readOnly)document.querySelector('#add-operation').onclick=()=>form();
 if(!readOnly)section.querySelectorAll('[data-settle]').forEach(b=>b.onclick=()=>form(db.expenses.find(e=>e.id===b.dataset.settle)));
 section.querySelectorAll('[data-operation-receipt]').forEach(b=>b.onclick=()=>TrustReceipts.show(db.payments.find(p=>p.id===b.dataset.operationReceipt).voucher));
 section.querySelectorAll('[data-operation-file]').forEach(b=>b.onclick=async()=>{try{const blob=await Store.getFile(b.dataset.operationFile);if(!blob)return;const i=db.invoices.find(i=>i.id===b.dataset.operationFile);download(i.name,blob);}catch(error){document.querySelector('#operations-status').textContent=error.message||'تعذر فتح الملف.';}});
 document.querySelector('#export-operations').onclick=()=>download('Trust-M-operating-costs.csv',new Blob([M.csv([['تاريخ المصروف','البند','البيان','المستفيد','المرجع','القيمة','المسدد','الباقي'],...rows.map(e=>[e.date,e.operatingCategory,e.description,e.party,e.reference,e.amount,paid(e),M.money(e.amount-paid(e))])])],{type:'text/csv;charset=utf-8'}));
 }
 function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const field=(name,label,type='text',value='',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
 function form(existing){const focus=document.activeElement,remaining=existing?M.money(existing.amount-paid(existing)):0;dialog.innerHTML=`<div class="detail-header"><h2 id="operations-title">${existing?'سداد مصروف تشغيل':'مصروف تشغيل جديد'}</h2><button class="close-detail" aria-label="اقفل">×</button></div><form class="finance-form">${existing?`<p class="wide">${esc(existing.operatingCategory)} · ${esc(existing.party)} · الباقي ${money(remaining)} جنيه</p>`:`<label>البند<select name="category">${categories.map(c=>`<option>${c}</option>`).join('')}</select></label>${field('date','تاريخ المصروف','date',today,'required')}${field('amount','قيمة المصروف','number','','required min="0.01" max="999999999999" step="0.01"')}${field('party','المستفيد / المورد','text','','required maxlength="150"')}${field('description','البيان','text','','required maxlength="500"')}${field('reference','مرجع المصروف / الفاتورة','text','','required maxlength="100"')}${field('file','الفاتورة (اختياري، PDF أو صورة حتى 10 ميجا)','file','','accept="application/pdf,image/jpeg,image/png"')}`}<label>طريقة الدفع<select name="method"><option value="Cash">كاش</option><option value="Bank transfer">تحويل بنكي</option><option>InstaPay</option><option value="Cheque">شيك</option></select></label>${field('paymentDate','تاريخ الدفع','date',today,'required')}${field('paid','المبلغ المدفوع دلوقتي','number',existing?remaining:0,`required min="${existing?'0.01':'0'}" max="${existing?remaining:999999999999}" step="0.01"`)}<p class="wide">لو المصروف لسه متدفعش سيب المدفوع صفر. لو فيه دفعة، هيتجهز سند صرف تلقائي.</p><p class="form-error wide" role="alert"></p><div class="form-actions"><button type="button" id="cancel-operation" class="quiet-button">إلغاء</button><button class="gold-button" type="submit">احفظ</button></div></form>`;
 const close=()=>dialog.close();dialog.querySelector('.close-detail').onclick=close;dialog.querySelector('#cancel-operation').onclick=close;dialog.addEventListener('close',()=>focus?.isConnected&&focus.focus(),{once:true});
 dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const button=event.submitter;button.disabled=true;try{const f=new FormData(event.target),cost=existing?existing.amount:Number(f.get('amount')),payment=Number(f.get('paid'));if(!Number.isFinite(cost)||cost<=0||cost>999999999999||!Number.isFinite(payment)||payment<0||payment>cost)throw Error('راجع قيمة المصروف والمدفوع؛ المدفوع ماينفعش يزيد عن الباقي.');const file=f.get('file'),fileId=crypto.randomUUID(),expenseId=existing?.id||crypto.randomUUID(),paymentId=crypto.randomUUID();if(file?.size&&(!['application/pdf','image/jpeg','image/png'].includes(file.type)||file.size>10*1024*1024))throw Error('اختار PDF أو صورة لحد 10 ميجا.');let voucher;
 db=await Store.update(next=>{if(!existing&&next.expenses.some(e=>e.reference===String(f.get('reference')).trim()))throw Error('مرجع المصروف ده مسجل قبل كده.');let expense=next.expenses.find(e=>e.id===expenseId);if(!expense){expense={id:expenseId,project:'company-overhead',date:f.get('date'),amount:M.money(cost),category:'Overhead',operatingCategory:f.get('category'),party:String(f.get('party')).trim(),description:String(f.get('description')).trim(),reference:String(f.get('reference')).trim()};next.expenses.push(expense);}const already=M.sum(next.payments.filter(p=>p.linkedExpense===expenseId),p=>p.amount);if(payment>M.money(expense.amount-already))throw Error('فيه دفعة اتسجلت؛ المدفوع أكبر من الباقي الحالي.');if(payment>0){const p={id:paymentId,project:'company-overhead',date:f.get('paymentDate'),amount:M.money(payment),direction:'out',party:expense.party,description:expense.description,method:f.get('method'),reference:'OP-'+paymentId,linkedExpense:expenseId};voucher=TrustReceipts.issue(next,p,'مصروفات تشغيل الشركة');next.payments.push(p);}if(file?.size)next.invoices.push({id:fileId,project:'company-overhead',date:expense.date,number:expense.reference,party:expense.party,amount:expense.amount,linked:expenseId,name:file.name,type:file.type,size:file.size});},file?.size?{id:fileId,blob:file}:undefined);dialog.close();draw();if(voucher)TrustReceipts.show(voucher);
 }catch(e){dialog.querySelector('.form-error').textContent=e.message;}finally{busy=false;button.disabled=false;}};dialog.showModal();}
 draw();
})();
